### ISSUE TITLE
Searching for types in the EE10 Javadoc leads to a 404 page

### ISSUE THREAD

**Issue by Azquelt** [jakartaee/platform#613]
**Describe the bug**

When I search for a type in the [EE10 Platform Javadoc][platform-jd], the [EE10 Web Profile Javadoc][web-jd] or the [EE10 Core Profile Javadoc][core-jd], it takes me to the wrong URL, leading to a 404 page.

**To Reproduce**
1. Go to the [EE10 Platform Javadoc][platform-jd]
2. In the search box at the top right, search for CreationalContext
3. Press Enter, or click on the CreationalContext type
4. You are taken to https://jakarta.ee/specifications/platform/10/apidocs/undefined/jakarta/enterprise/context/spi/CreationalContext.html, which is not the correct page

**Expected behavior**

You should be taken to https://jakarta.ee/specifications/platform/10/apidocs/jakarta/enterprise/context/spi/CreationalContext.html (which then redirects to https://jakarta.ee/specifications/platform/10/apidocs/jakarta/enterprise/context/spi/creationalcontext)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 37
 - Browser: Firefox
 - Version: 109.0.1

**Smartphone (please complete the following information):**
- Not tested

**Additional context**

This doesn't seem to affect any of the component specifications. I can search for CreationalContext in the [CDI 4.0 Javadoc][cdi-jd] and it takes me to the correct place.

It also doesn't affect searching for _packages_ in the platform Javadoc.

[platform-jd]: https://jakarta.ee/specifications/platform/10/apidocs/
[web-jd]: https://jakarta.ee/specifications/webprofile/10/apidocs/
[core-jd]: https://jakarta.ee/specifications/coreprofile/10/apidocs/
[cdi-jd]:https://jakarta.ee/specifications/cdi/4.0/apidocs/

[AB#50](https://dev.azure.com/jakarta-ee-azdo/7cf9a9d3-9854-41e0-9a66-99506a9ed874/_workitems/edit/50)

**Comment by lprimak** [comment]
Checked & Fixed in Jakarta EE 11 (current main branch)

**Comment by Azquelt** [comment]
Thank you!

**Comment by OndroMih** [comment]
I'm glad it works for EE 11. But do you really think it's enough to fix it only for EE 11? This should work also for EE 10, even after EE 11 is out. Does anybody know how to fix it for EE 10 too?

**Comment by lprimak** [comment]
It would require EE 10 patch release

**Comment by scottmarlow** [comment]
> Checked & Fixed in Jakarta EE 11 (current main branch)

Could someone please provide a link to the github commit that contains the fix so we can all better understand what changed to fix the search issue on EE 11.  Thanks!

**Comment by lprimak** [comment]
Good job!
