### ISSUE TITLE
JDBC 4.3 being required JDBC level for Jakarta EE 11

### ISSUE THREAD

**Issue by jhanders34** [jakartaee/platform#618]
**Is your feature request related to a problem? Please describe.**
Previous Jakarta platforms specification state JDBC 4.2 as the JDBC API level to be used for Jakarta EE.  The minimum Java SE level in Jakarta EE 10 changed to Java EE 11 which provides JDBC 4.3 API.  Jakarta EE 10 cannot be changed now, but we should make sure to switch to JDBC 4.3 especially since moving to Java SE 21.

**Describe the solution you'd like**
Update the platform specification(s) and any other component specifications that reference JDBC to say JDBC 4.3 API instead of 4.2.  Specification section 6.2.3.2 in the Jakarta EE 10 platform specification is an example of a location to be updated.  Web Profile may also need to be updated.

**Describe alternatives you've considered**
Could allow for use of JDBC 4.2 or 4.3 API in the specification, but that seems odd to have.

[AB#65](https://dev.azure.com/jakarta-ee-azdo/7cf9a9d3-9854-41e0-9a66-99506a9ed874/_workitems/edit/65)

**Comment by hantsy** [comment]
Jdbc 4.3 will be part of Jakarta EE? I remember currently Jdbc is not related to the Java EE/Jakarta EE, most of the APIs are defined in Java SE.

**Comment by jhanders34** [comment]
Yes JDBC is defined in Java SE, but Java EE and now Jakarta EE Platform has included a specific level of JDBC API to be used with EE.  Obviously JDBC is an underlying technology used with Jakarta Persistence.

**Comment by lukasj** [comment]
is https://jakartaee.github.io/persistence/latest-nightly/nightly.html#a14205 what you are looking for? Note that the link points to the most recent spec doc built from master

**Comment by edburns** [comment]
@jhanders34  does https://github.com/jakartaee/platform/issues/618#issuecomment-1765180714 work for your needs?

**Comment by jhanders34** [comment]
I think that is a good first start.  JDBC 4.2 is also discussed in the platform spec and that is for sure where I would like it to be addressed.  If there are other specifications like Persistence that should be updated. I will have to search through them all and see which ones those are.  I suppose getting issues opened on those API repositories would be valid as well.  Right now the website is having issues so I cannot see the persistence 3.1 spec pdf to see what it used to look like.

**Comment by jhanders34** [comment]
It looks like most other specs reference jdbc 4.3 in their links for JDBC.  Connectors is referencing 4.1 still, but that feature is not getting any update in Jakarta EE 11.  I think with what Lukas has done for Persistence and an update to the platform spec (and maybe something should be added to web profile spec as well), I think this will be satisfied.

**Comment by edburns** [comment]
At the 2023-10-17 call, the idea was surfaced that, instead of naming specific JDBC versions, **instead** we say something to the effect of, "the minimum JDBC version required to be supported is the one that goes along with the minimum required JDK version for this version of the EE platform and web profiles".

**Comment by bstansberry** [comment]
+1 to adding clarification about the relationship between SE and JDBC. We should avoid doing it in way though that has the effect of implying a JDBC version that differs from the SE level being used. (Ed's language above discusses both JDBC and SE in terms of minimums, which is good.)

I'll note that AFAICT the only platform spec reference to JDBC 4.2 is not an explicit requirement for that version. In 6.2.3.2 it just says 

'The JDBC 4.2 specification is available at https://jcp.org/en/jsr/detail?id=221 .'

Personally I wouldn't interpret that as a version requirement, but I'm sure many people would, and at best it is confusing.

**Comment by hantsy** [comment]
What is the future of JDBC?

It will be part of Jakarta EE, or still exists as JDK modules.

It is possible to introduce virtual thread support in Jdbc?

**Comment by edburns** [comment]
Seeking review from @jhanders34  of PR #775 .
