### ISSUE TITLE
Tracking Jakarta Annotations 3.0

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform#701]
**Is your feature request related to a problem? Please describe.**
We need a major 3.0 release of Jakarta Annotations for the removal of the jakarta.annotation.ManagedBean annotation deprecated in EE 10.

**Describe the solution you'd like**
A 3.0 Jakarta Annotations [release plan](https://projects.eclipse.org/projects/ee4j.ca/releases/3.0) has been created and the 3.0 release needs to be tracked for EE 11 

**Describe alternatives you've considered**
None

**Additional context**
A "Pruning managed beans from the component specs" email thread on the dev list starts here:
https://www.eclipse.org/lists/jakartaee-platform-dev/msg04007.html

[AB#43](https://dev.azure.com/jakarta-ee-azdo/7cf9a9d3-9854-41e0-9a66-99506a9ed874/_workitems/edit/43)
[AB#35](https://dev.azure.com/jakarta-ee-azdo/7cf9a9d3-9854-41e0-9a66-99506a9ed874/_workitems/edit/35)

**Comment by edburns** [comment]
AB#41

**Comment by edburns** [comment]
Discussed with nominal project lead @m0mus about the acceptability of removing `ManagedBean`. He sees no technical problem with the removal. At the same time, Dmitry cited a desire to have someone else be the spec project lead for this spec project for EE11.

**Comment by arjantijms** [comment]
PR in Jakarta Annotations project: https://github.com/jakartaee/common-annotations-api/pull/115
