### ISSUE TITLE
Compatibility certification request for Helidon 4.0 for Jakarta EE 10 Core Profile

### ISSUE THREAD

**Issue by edbratt** [jakartaee/platform#869]
- [x] Organization Name ("Organization") and, if applicable, URL:
  [Oracle](https://oracle.com)
- [x] Product Name, Version and download URL (if applicable):
  [Helidon v4.0.6](https://helidon.io/)
- [x] Specification Name, Version and download URL:
  [Jakarta EE 10 Core Profile](https://jakarta.ee/specifications/coreprofile/10/), [Specification Document](https://jakarta.ee/specifications/coreprofile/10/jakarta-coreprofile-spec-10.0) 
- [x] TCK Version, digital SHA-256 fingerprint and download URL:
  See below
- [x] Public URL of TCK Results Summary:
  [Jakarta EE 10, Core Profile Results](https://github.com/helidon-io/helidon/wiki/MicroProfile-6-and-Jakarta-EE-10-Core-Profile-Certification,-Helidon-4#jakarta-ee-10-core-profile)
- [x] Any Additional Specification Certification Requirements:
  None
- [x] Java runtime used to run the implementation:
  JDK 21
- [x] Summary of the information for the certification environment, operating system, cloud, ...:
  Ubuntu 20.04
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

#### Annotations TCK

[jakarta-annotations-tck 2.1.1](https://download.eclipse.org/jakartaee/annotations/2.1/jakarta-annotations-tck-2.1.1.zip):

SHA-256: 8c2131d51c75cde4be74382f662519f9fd439f4ce4dd60832ed55b796e5f72f3

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

#### CDI TCK
Tests from [CDI TCK 4.0.12 Distribution](https://download.eclipse.org/jakartaee/cdi/4.0/cdi-tck-4.0.12-dist.zip)

SHA-256: 9a78168b529e1a072127e525259bbce9bdc4da2f49deb416363ee2b0a145d14f

[jakarta-cdi-tck 4.0.12](https://repo1.maven.org/maven2/jakarta/enterprise/cdi-tck-api/4.0.12/cdi-tck-api-4.0.12.jar):

Tests run: 712, Failures: 0, Errors: 0, Skipped: 0

Excluded: org/jboss/cdi/tck/tests/definition/bean/types/ManagedBeanTypesTest.java

TCK-Challenge: https://github.com/jakartaee/cdi-tck/issues/485 (Accepted and closed)

[jakarta-cdi-lang-model-tck 4.0.12](https://repo1.maven.org/maven2/jakarta/enterprise/cdi-tck-lang-model/4.0.12/cdi-tck-lang-model-4.0.12.jar):

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

#### Core Profile TCK
[jakarta-core-profile-tck 10.0.3](https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-core-profile-tck-10.0.3.zip):

SHA-256: a531a6ffc1eedfced6383a519013d176060b8280189141dcd626c26aad8502ac

Tests run: 13, Failures: 0, Errors: 0, Skipped: 0

#### Inject TCK
[jakarta.inject-tck 2.0.2](https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.2-bin.zip):

SHA-256: 23bce4317ca061c3de648566cdf65c74b57e1264d6891f366567955d6b834972

Tests run: 50, Failures: 0, Errors: 0

#### JSON Binding TCK
[jakarta-jsonb-tck 3.0.0](https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee10/promoted/eftl/jakarta-jsonb-tck-3.0.0.zip):

SHA-256: 954fd9a3a67059ddeabe5f51462a6a3b542c94fc798094dd8c312a6a28ef2d0b

Tests run: 295, Failures: 0, Errors: 0, Skipped: 5

#### JSON Processing TCK
Test from [Jakarta JSON P TCK 2.1.1](https://download.eclipse.org/jakartaee/jsonp/2.1/jakarta-jsonp-tck-2.1.1.zip)

SHA-256: 949f203de84deffa8c7892b555918e42f1dd220ccb7b6800741ea58af62737c1

[jakarta-jsonp-tck 2.1.1](https://repo1.maven.org/maven2/jakarta/json/jakarta.json-tck-tests/2.1.1/jakarta.json-tck-tests-2.1.1.jar):

Tests run: 179, Failures: 0, Errors: 0, Skipped: 0

[jakarta-jsonp-pluggability-tck 2.1.1](https://repo1.maven.org/maven2/jakarta/json/jakarta.json-tck-tests-pluggability/2.1.1/jakarta.json-tck-tests-pluggability-2.1.1.jar):

Tests run: 18, Failures: 0, Errors: 0, Skipped: 0

#### RESTFul Web Services TCK
[jakarta-restful-ws-tck 3.1.5](https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-restful-ws-tck-3.1.5.zip):

SHA-256: 93bf5bd22a217fd1950026feaeec6a234c7a67137657d64a13bb56b105b0fb2e

Tests run: 2647, Failures: 0, Errors: 0, Skipped: 132

**Comment by ivargrimstad** [comment]
+1, LGTM

Great work, and congrats with the certification. Please continue the process to get Helidon listed on the Jakarta EE web page.
