### ISSUE TITLE
Clarification on older schemas required for EE 11 implementations to support

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/platform#906]
In EE 11, what exactly are we trying to accomplish with the `Appendix A` rules?

For reference current `Appendix A` https://jakarta.ee/specifications/platform/10/jakarta-platform-spec-10.0#a3447 or https://jakarta.ee/specifications/platform/9/jakarta-platform-spec-9#a3447 (both have the same text):

> This appendix describes Document Type Definitions (DTDs) and XML schemas for Deployment Descriptors from previous versions of the Java™ EE and Jakarta™ EE specifications. All Jakarta EE 9 products are required to support the DTDs and schemas specified by Jakarta EE 8, as well as the schemas specified in this version of the specification. This ensures that applications written to the previous version of the Jakarta EE specification can be deployed on products supporting the current version of this specification. Support for versions of DTDs and schemas prior to Jakarta EE 8 is optional. In addition, there are no restrictions on mixing versions of supported deployment descriptors in a single application; any combination of valid deployment descriptor versions must be supported.

In the above quoted text, `this version of the specification` refers to EE 9 and how EE 9 implementations must support the schemas of the previous (EE 8) release.  Optionally, earlier schemas (e.g. Java EE/J2EE) can be supported but are not required.

What is the `Appendix A` requirement for EE 11 and Jakarta EE schemas?

One schema to consider is https://jakarta.ee/xml/ns/jakartaee/ejb-jar_4_0.xsd which is listed on https://jakarta.ee/xml/ns/jakartaee/ as being part of Jakarta EE 9/10/11 but has not changed for any of these EE releases.

Another schema is https://jakarta.ee/xml/ns/jakartaee/beans_4_1.xsd which changed the version number for EE 11 but is otherwise still compatible with EE 10 (https://jakarta.ee/xml/ns/jakartaee/beans_4_0.xsd).

Do EE 11 applications need to update their `beans_3_0.xsd` references to beans_4_1.xsd/beans_4_0.xsd? but they can still use the (EE 9) ejb-jar_4_0.xsd?

[AB#200](https://dev.azure.com/jakarta-ee-azdo/7cf9a9d3-9854-41e0-9a66-99506a9ed874/_workitems/edit/200)

**Comment by ivargrimstad** [comment]
> Do EE 11 applications need to update their `beans_3_0.xsd` references to beans_4_1.xsd/beans_4_0.xsd? but they can still use the (EE 9) ejb-jar_4_0.xsd?

I think the answer to this question is 'Yes' since the behavior of the empty beans.xml changed the default discovery mode from 'all' to 'annotated'.  At least in the case where there is an empty beans.xml and the application depends on the default behavior.

**Comment by edburns** [comment]
Thanks for opening this @scottmarlow. I propose the following:

1. Change the name of Appendix A to "Deployment Descriptors". Remove "Previous Version".

1. We change this text:

   > This appendix describes Document Type Definitions (DTDs) and XML schemas for Deployment Descriptors from previous versions of the Java™ EE and Jakarta™ EE specifications.
   
   to be (bold for discussion emphasis only. Not a part of the suggested change.):

   > This appendix describes Document Type Definitions (DTDs) and XML schemas for Deployment Descriptors from **current and previous** versions of the Java™ EE and Jakarta™ EE specifications.

1. We change this text:

   > All Jakarta EE 9 products are required to support the DTDs and schemas specified by Jakarta EE 8, as well as the schemas specified in this version of the specification. 

   to be (bold for discussion emphasis only. Not a part of the suggested change.):

   > All Jakarta EE 9 products are required to support the DTDs and schemas specified by Jakarta EE 8, as well as the schemas specified in **the current version** of the specification.

1. We author and include text that codifies what we agreed in the platform call on [2024-03-05](https://jakartaee.github.io/platform/minutes/2024/2024-03-05.html) and also on [the platform-dev list](https://www.eclipse.org/lists/jakartaee-platform-dev/msg04432.html). We include this text after the introductory paragraph.

   Here is a proposal for the text, based on the meeting minutes and email.
   
   > If a component specification is modified during an EE release cycle, and that newer version of the specification is included in the EE release cycle, any XSD files must have their version number and file names updated accordingly to match the version of the component specification included in the corresponding EE release.
   > This update must happen regardless whether or not there are normative changes to the XSD files.

**Comment by edburns** [comment]
Discussed at 2024-07-09 Platform dev call. The above wording passed without comment.
