### ISSUE TITLE
Compatibility certification request for SofaEE 1.0.0 for Web Profile

### ISSUE THREAD

**Issue by SofaEE** [jakartaee/platform#957]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Ant Group CO., Ltd](https://www.sofastack.com/web/page/sofaEE)
- [x] Product Name, Version and download URL (if applicable):<br/>
  [SofaEE 1.0.0](https://www.sofastack.com/web/page/sofaEE)
- [x] Specification Name, Version and download URL:<br/>
   [Jakarta EE Platform, Web Profile 8](https://jakarta.ee/specifications/platform/8/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta EE Platform TCK 8.0.2](https://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip) 
 `SHA-256: 14a21b617bb646055c2952f1422ec04a71389fb37301e1c2969f6c3700aee965`
- [x] Public URL of TCK Results Summary:<br/>
  [SofaEE TCK Results](https://www.sofastack.com/web/docs/sofaEETCKResult)
- [x] Any Additional Specification Certification Requirements:<br/>
 [Jakarta Dependency Injection 1.0 TCK](https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip)
`SHA-256: b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f`
 [Jakarta Contexts and Dependency Injection 2.0 TCK](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip),
`SHA-256: 75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808`
[Jakarta Bean Validation 2.0 TCK](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip)
`SHA-256: b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974`
- [x] Java runtime used to run the implementation:<br/>
 Java(TM) SE Runtime Environment (build 1.8.0_411-b09)
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  ```
  OS version: Ant Group Enterprise Linux Server 7.2 (Paladin)
  Database version:   Apache Derby Network Server 10.14.2.0
  Database JDBC Driver and version:  Apache Derby 10.14.2.0
  ```
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by hantsy** [comment]
@SofaEE I can not find a downloadable link of this Jakarta EE product in the sofatech website, and the top level link *文档* got a 404 error.

**Comment by SofaEE** [comment]
> @SofaEE I can not find a downloadable link of this Jakarta EE product in the sofatech website, and the top level link _文档_ got a 404 error.

Since this is a commercial product, there is no open-source download link available. Furthermore, given that the context mentions _download URL   (if applicable)_, only the product name, version, and official website link have been provided.

The document link is about an introduction to the entire SOFA Stack product, and currently, there isn't a separate introduction specifically for SofaEE. If needed, we can provide that information later.
