### ISSUE TITLE
Compatibility certification request for [JEUS 9] for [Platform]

### ISSUE THREAD

**Issue by TmaxEE** [jakartaee/platform#958]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
[TmaxSoft Co., Ltd](https://www.tmaxsoft.com/)
- [x] Product Name, Version and download URL (if applicable):<br/>
[JEUS 9](http://www.tmaxsoft.com/jakee/install/jeus9/jeus9-b15.zip)
- [x] Specification Name, Version and download URL:<br/>
[Jakarta EE Platform 9, Full Platform](https://jakarta.ee/specifications/platform/9/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
[Jakarta EE Platform TCK 9.0.2](https://download.eclipse.org/jakartaee/platform/9/jakarta-jakartaeetck-9.0.2.zip)
SHA-256: ffd78f41592f69c846f52f80df3641191a984fd15740be56e83c0a73e9e546b8
- [x] Public URL of TCK Results Summary:<br/>
[https://www.tmaxsoft.com/jakee/JEUS9_JakartaEE9_Certification_Summary.html](https://www.tmaxsoft.com/jakee/JEUS9_JakartaEE9_Certification_Summary.html)
- [x] Any Additional Specification Certification Requirements:<br/>
Jakarta Bean Validation 3.0 TCK
Jakarta Contexts and Dependency Injection 3.0 TCK
Jakarta Dependency Injection 2.0 TCK
Jakarta Debugging Support for Other Languages 2.0 TCK
- [x] Java runtime used to run the implementation:<br/>
Open JDK 1.8.0_402
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
Apache Derby, Ubuntu 20.04.4 LTS (GNU/Linux 5.15.0-100-generic x86_64)
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
The SHA-256 for the Jakarta EE Platform TCK 9.0.2 does not match. It is the SHA-256 for the 9.0.1 TCK which is listed 

Please update the issue (and TCK results page) to either point to TCK 9.0.1, or update the SHA to the one corresponding to 9.0.2. 

Either approach is fine as long as it reflects the version of the TCK  that were used.

**Comment by TmaxEE** [comment]
Thank you for checking.

I updated SHA-256 for the Jakarta EE Platform TCK 9.0.2.
