### ISSUE TITLE
Compatibility certification request for AliEE 1.0.0 for Web Profile

### ISSUE THREAD

**Issue by AliyunAliEE** [jakartaee/platform#973]
- [x] Organization Name ("Organization") and, if applicable, URL:
[Alibaba Cloud Computing](https://help.aliyun.com/zh/edas/product-overview/what-is-alibaba-cloud-application-server?spm=a2c4g.11186623.0.0.72385806mPZpST)
- [x]  Product Name, Version and download URL (if applicable):
[Aliee 1.0.0](https://help.aliyun.com/zh/edas/product-overview/what-is-alibaba-cloud-application-server?spm=a2c4g.11186623.0.0.72385806mPZpST)
- [x] Specification Name, Version and download URL:
[Jakarta EE Platform, Web Profile 8](https://jakarta.ee/specifications/platform/8/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:
[Jakarta EE Platform TCK 8.0.2](https://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip) 
  SHA-256: 14a21b617bb646055c2952f1422ec04a71389fb37301e1c2969f6c3700aee965
- [x] Public URL of TCK Results Summary:
[TCK Results](https://aliyuque.antfin.com/ypgo6v/hq29g8/qu4iyd3mk2f026kg#)
- [x] Any Additional Specification Certification Requirements:
[Jakarta Dependency Injection 1.0 TCK](https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip)
SHA-256: b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f
[Jakarta Contexts and Dependency Injection 2.0 TCK](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip),
SHA-256: 75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808
[Jakarta Bean Validation 2.0 TCK](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip)
SHA-256: b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974
- [x] Java runtime used to run the implementation:
Java(TM) SE Runtime Environment (build 1.8.0_411-b09)
- [x] Summary of the information for the certification environment, operating system, cloud, ...:
OS version: Ant Group Enterprise Linux Server 7.2 (Paladin)
Database version:   Apache Derby Network Server 10.14.2.0
Database JDBC Driver and version:  Apache Derby 10.14.2.0
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by dblevins** [comment]
@AliyunAliEE Is there a link to download the server?  Note, Alibaba would need to be a member of the Jakarta EE Working Group to get approval.  https://jakarta.ee/membership/members/
