### ISSUE TITLE
Compatibility certification request for WildFly Preview for Jakarta EE 11 Core Profile

### ISSUE THREAD

**Issue by jamezp** [jakartaee/platform#978]
- [X] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Red Hat](https://redhat.com)
- [X] Product Name, Version and download URL (if applicable):<br/>
  [WildFly Preview 34.0.0.Final](https://github.com/wildfly/wildfly/releases/download/34.0.0.Final/wildfly-preview-34.0.0.Final.zip)
- [X] Specification Name, Version and download URL:<br/>
   [Jakarta EE Core Profile v 11](https://jakarta.ee/specifications/coreprofile/11)
- [X] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta EE Core Profile TCK 11.0 (Staged Release)](https://eclipse.mirror.rafal.ca/ee4j/jakartaee-tck/jakartaee11/staged/eftl/jakarta-core-profile-tck-11.0.0.zip)
 SHA-256: `0357bfab7025972edb2bf50277b6b4206b499a2961bc94e783f34782cc4a9bda`
- [X] Public URL of TCK Results Summary:<br/>
  [Java 17 Test Results](https://github.com/wildfly/certifications/blob/EE11/WildFly_Preview_34.0.0.Final/jakarta-core-jdk17.adoc)
  [Java 21 Test Results](https://github.com/wildfly/certifications/blob/EE11/WildFly_Preview_34.0.0.Final/jakarta-core-jdk21.adoc)
- [X] Any Additional Specification Certification Requirements:<br/>
     Jakarta Annotations TCK 
  [jakarta-annotations-tck-3.0.0.zip](https://download.eclipse.org/jakartaee/annotations/3.0/jakarta-annotations-tck-3.0.0.zip)
  SHA-256: `9421c6ca66274d32dfb408848f75a42d57f120599fe0d8403c5c5c1141d5ac4d`
  
  Jakarta CDI TCK 
  [cdi-tck-4.1.0-dist.zip](https://download.eclipse.org/jakartaee/cdi/4.1/cdi-tck-4.1.0-dist.zip)
  SHA-256: `446029ee1ce694d2a9ae8893d16be7afd7e1c0ed8705064b7095af174cf97ea0`
  
  Jakarta Dependency Injection TCK 
  [jakarta.inject-tck-2.0.2-bin.zip](https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.2-bin.zip)
  SHA-256: `23bce4317ca061c3de648566cdf65c74b57e1264d6891f366567955d6b834972`
  
  Jakarta JSON Binding 
  [jakarta-jsonb-tck-3.0.0.zip](https://download.eclipse.org/jakartaee/jsonb/3.0/jakarta-jsonb-tck-3.0.0.zip)
  SHA-256-`954fd9a3a67059ddeabe5f51462a6a3b542c94fc798094dd8c312a6a28ef2d0b` 
  
  Jakarta JSON Processing 
  [jakarta-jsonp-tck-2.1.1.zip](https://download.eclipse.org/jakartaee/jsonp/2.1/jakarta-jsonp-tck-2.1.1.zip)
  SHA-256: `949f203de84deffa8c7892b555918e42f1dd220ccb7b6800741ea58af62737c1`
  
  Jakarta RESTful Web Services 
  [jakarta-restful-ws-tck-4.0.1.zip](https://download.eclipse.org/jakartaee/restful-ws/4.0/jakarta-restful-ws-tck-4.0.1.zip)
  SHA-256: `b6290c1b5b3d2fdd9cc700a999243492a7e27b94a9b6af1974ff4dc5bfbf98f2`
- [X] Java runtime used to run the implementation:<br/>
  Java 17
  
````
openjdk version "17.0.13" 2024-10-15
OpenJDK Runtime Environment (Red_Hat-17.0.13.0.11-1) (build 17.0.13+11)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.13.0.11-1) (build 17.0.13+11, mixed mode, sharing)
  ````
  Java 21

  ````
  openjdk version "21.0.5" 2024-10-15
  OpenJDK Runtime Environment (Red_Hat-21.0.5.0.11-1) (build 21.0.5+11)
  OpenJDK 64-Bit Server VM (Red_Hat-21.0.5.0.11-1) (build 21.0.5+11, mixed mode, sharing)
  ````
- [X] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Fedora Linux 41
- [X] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [X] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by jhanders34** [comment]
In your results, the `j` is missing from the rest tck link.  You may want to fix that so the it doesn't say `akarta`

**Comment by scottmarlow** [comment]
> In your results, the `j` is missing from the rest tck link. You may want to fix that so the it doesn't say `akarta`

Thanks, just add the missing `j` for both TCK results.

**Comment by jamezp** [comment]
Oh shoot. I'll get that fixed ASAP @edburns. Nice catch.

**Comment by ivargrimstad** [comment]
The ongoing mentor review of https://github.com/jakartaee/specifications/pull/782 has resulted in a new build of the TCK.

**Comment by jamezp** [comment]
Has the respin been done? These results are from the respin on 30 October. If there is another respin, once it's available I can run against it then.

**Comment by scottmarlow** [comment]
> Has the respin been done? These results are from the respin on 30 October. If there is another respin, once it's available I can run against it then.

Looks like work in progress still (https://ci.eclipse.org/jakartaee-tck/job/11/job/jakarta-core-profile-tck-maven-central/11 had a failure).

**Comment by jamezp** [comment]
Thanks @scottmarlow. I don't have permissions to see that, but I trust you :)

**Comment by starksm64** [comment]
No, the respin is in progress. I'll post when it is done.

**Comment by starksm64** [comment]
Restaged, https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee11/staged/eftl/jakarta-core-profile-tck-11.0.0.zip

```
***********************************************************************************
***                        TCK bundle information                               ***
*** Name:       jakarta-core-profile-tck-11.0.0.zip                                     ***
*** Bundle Copied to URL:    http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee11/staged/eftl//jakarta-core-profile-tck-11.0.0.zip ***
*** Date and size: date: 2024-11-14 18:20:10.444442915 +0000, size(b): 224670        ***
*** SHA256SUM: 0357bfab7025972edb2bf50277b6b4206b499a2961bc94e783f34782cc4a9bda ***
***                                                                             ***
***********************************************************************************
```

**Comment by jamezp** [comment]
Updates to the wildfly-tck-runner are running in a PR now https://github.com/wildfly/wildfly-tck-runners/pull/206.

**Comment by jamezp** [comment]
Everything has been updated and is passing with WildFly 34.
