### ISSUE TITLE
Additional minor security manager permissisons cleanup

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform#997]
**Is your feature request related to a problem? Please describe.**
The 3.5.1. Code Authorization section of the m4 milestone is still referring to requirements for a permissions.xml and implied SecurityManager permissions. This needs to be updated to state that there is no support for this in EE11.

**Describe the solution you'd like**
State that running with a SecurityManager is not supported and no application permissions requirements exist.

**Additional context**
The SecurityManager usage has been removed from EE11 and all references to its use need to be updated to reflect that.

**Comment by jhanders34** [comment]
I already removed this section in the main branch.  Just need to make a new M5 of the platform spec if we want to see all the updates I have made over the last few months.

**Comment by starksm64** [comment]
Yes, I see that now that I am in in the docs. There are a couple other minor references that permissions that I have made changes to for further cleanup.
